### ISSUE TITLE
HOW?

### ISSUE THREAD

**Issue by Zibri** [whtsky/mala#1]
I copied the example:

from maga import Maga
from mala import get_metadata

class Crawler(Maga):
    async def handle_get_peers(self, infohash, addr):
        pass

    async def handle_announce_peer(self, infohash, addr, peer_addr):
        metainfo = await get_metadata(
            infohash, peer_addr[0], peer_addr[1], loop=self.loop
        )

crawler = Crawler()
crawler.run(port=0)

How to get the hash name or size? metainfo returns false...

**Comment by Zibri** [comment]
Nevermind, I got it. Anyway it's slow. simDHT is way better.

**Comment by itdaniher** [comment]
I'm not acquainted with simDHT, but project "mana" which uses both Maga and Mala also uses uvloop for faster networking. It's 75 lines, might be worth checking out. https://github.com/itdaniher/mana/blob/master/mana.py

**Comment by kingctan** [comment]
is the metainfo the content of torrent file? 
but how to save metainfo to file? I can't do that.
@itdaniher @Zibri 
Thanks.
